language: ruby
rvm:
- 2.0.0
bundler_args: "--without production"
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: bbgrO4r1gO7IlhAzxGgK9OBZDjFvdoj0V5qnollu7NlWl6nhwP/DI5qpVP3fE/c8Hh+5hVoasr5HFqNzSS8YSoQ+AVPhWpmPJpCyFBP3r9bXbYrAgBPvVOEPRebOWkoIdcTH5tshFpg9w5Wah5ulfGw/BKbFLYTM6/gfMswA7GQou38Q+rq33vIKglwDvpU7ppJbLitOUQHW9xAAmwzJzp12qlkFgjPnWtPYasAwL3wH/nY4ARAjX6j+2XDpl+pR3XmUJ3eAPdjeG7Wt8WLDfPD+UfdZYdBmv9hX2rdFtw88/keSy7j1clGws0eZ8ZEVp28/fvCWPAyhNxIDnZZgAocZ0CeMW39nnoxFGeCvp3ZGrOvA7ipwiWPjSw0hfAqAn+O64SSq1ki1pDVz4RoiN9hS8RiQYtC/uzzaidFQRLAdvyki822vj+9+lT2aLhyTHnOr/KJ4TsQKpua4LB5SJegJBKKubXy7EKkKWRALNqGwJsii++UciWy0OTqpMzEjjx37gLRRrnfwlF+N9oT6fNNV23u7ZZ5naZKVa9iheSyRe/p8xWnfpQZaZQ0h4eKi9bxa1gY2cORDyt6uzvqZLlENJt+sUzl/e5VHCXst+6kZCq7ZLPoJ1JO5+zOkj+fj+eefoWFLAyzVtn6Y+kV2LEUj9ikHRiDgI3QX0MgSdUo=
  app: safe-scrubland-32633
  on:
    repo: Adrian-Monti/Shoe_Addict_App
  run: "rake db:migrate"
env:
  global:
  - secure: GKZa+rX7/5r6s6L9KdmWwo/s1l4Ok1WW6ersFncJ0F/mpwn1gAZ2rZNtjst6KTQXVDg9EQoTMXKmdfiS2bNrNjkQ/SLmy2UVusPqZSLrOqZt2w0Yy5I26/XlehuYulVccdvdKkec9jq8hJgpUrlm+sNI6Fpu0ODGeDVG8fymb2P8yzeiCfHst7F6UlkvwJ5VyEgDgDL7oRifRLWwhe+Yt14uGHZ0RN7L0O4qLHsmP3z2h61ekCiuxDfoLSfYxcyfByv4sqptNG4PXh/3qjyK2GLPhMVV9N5r7sknjKix2DYRvx8JL86/8X4DgQwbCk6EOEaPy4M/L/Z4cvdFDA64HXHqFbZYdq/mzpw73OgCkL8HE4hXw9Q59e9L/hAj4kJi7I5e4bPEroaY3EX5p5+ei1+q38hMBsORCjYdBzrXMqMSBMQjfG8hmZx9WYjXztZKgw9n5E3sv196zksPqMAbAxjxQqfNmqoPV8lA3ODsBQHbMSkRHPGmvVUURxKSckK9yiuyesG7RioL8QQ8EYX06vRSho9XfNGw8QHZbpnv+EV4PD89TFPcNcq+12yr7YzsfLM0te5NoTcWfDEnmMK2bKcsWNYN2y9X6tGl6zMO9RySzEimarUeoFS6DhbRfrnCrxbaPKksb48xPKeR3YK+ZMYfhxGhwfUOLVn2YQwQt+o=
  - secure: HBwQRI2p6mYezhvjZyhXNAGJ2PucAs2Y7ScAjPlV5z8Y8v597XBwdU8qmH273PyfYLx1o8aM9HO2e7wJC7KAJNCn9z/TrCrupaC8rQD1QQlptTylE3gmn9q8TyURaz4+6iRkn0HR77sfwIp3WYjlhuptTsiXuzQr6/r8kBwoxeotC1D+Y5NVgJCEZwPp3AQ0zztCdaswlp0W4ZMX3p4gecdMMZ9yr508EukumZseVezigP29/QC22fmo/I27h2UpBd8qooDW/pwEtDpmEqiHUGMFofQp8Xl0NlEgo6d4KaMENtpLaYVl5SKfWKaaPx9n2WSeGLSqkx+KpvxOi5OrMNbesZy4SktMlCYc4Q20mf5VSoMFLS2EXb8b46rQ9dAw1sv4/3LYkxmRis431D0S0di2skzNreLus7xqS7cqroL/mHvP0rlgXO1SCn4R6jk992XDrKam+wHTqejDv551UjCTAyBUwPMRKkn119agRqstYjDhhBS1gs6wY/DfSHU02mWqMNvnOfnttC84mMc8MAT5Yw+Eh81L2xIwHciu/2k1ldGO83k/3wz70lvSyEacXXZ92LtVtTNM7uE56JA1U4Jb3L2jhXCpmkbiDlJLT1o25zmOWA4wR3e2kEoUQ8fqQsX5zYauq2q//JY/UZGScObVYOUan64Sx/XGXKsJqr8=
