development:
  <<: *default
  database: shoe_addict_development

  username: <%= ENV['POSTGRES_USER'] %>

  password: <%= ENV['POSTGRES_PASSWORD'] %>

  host: localhost

test:
  <<: *default
  database: shoe_addict_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
